### ISSUE TITLE
Update CMS for Blog

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#397]
## Description
The CMS needs some additional features to be able to facilitate a blog hosted at crisiscleanup.org instead of blogger.com

## Tasks
- [x] Add the ability to upload photos and files into a Library.
- [x] Add the ability to embed photos and files from the Library, directly into the body of the blog post.
- [x] Add the ability to optionally expire a CMS item at an arbitrary timestamp.
- [x] **Bug**: Currently unable to load to library
- [ ] **Bug**: CMS item Title does not update on save.
- [x] We currently have a library table: `library_libraries` table. For discussion: We also need to create **lists**. Should Lists and Libraries be the same thing?

**Comment by aarontitus** [comment]
See new items about libraries and lists.
