### ISSUE TITLE
Create Matching Donations Admin Tool

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#403]
## Description
This module allows an Admin to bulk-send invitations to users to invite them to make matching donations to a Crisis Cleanup Partner organization of their choice. To start with, this will be a very manual process. We don't know the right formula, messaging, etc.
1. Aaron figures out how much money CCU can donate.
2. Aaron finds a list of high-performing users
3. Aaron experiments with different settings for `max_match`, `match_multiplier`, reminding people, etc., often in A-B batches to measure the most effective outcomes.
4. Aaron copies and pastes a batch of user emails into the Matching Donations Admin Tool (MDAT), sets a series of settings, and then sends the emails.
5. Those users receive an invitation to make a matching donation using a default email template. Non-user emails are ignored.
6. Invitations are logged in `user_users_matching_donations`. Donations, matches, and payouts are logged in `user_users_matching_donations_logs`.

## Tasks
Admin must be able to:
- [ ] Copy and paste user emails to be sent in batches.
- [ ] Set the incident associated with the batch.
- [ ] Set the `max_match` for each member of the batch, or the maximum CCU will match as a donation.
- [ ] Set the `max_multiplier` for each member of the batch. The rate at which Crisis Cleanup will match a donation. If 0, then Crisis Cleanup will not match the donation (e.g., match $10 with $0, for a total of $10). If 1, then Crisis Cleanup will match evenly (e.g., match $10 with $10, for a total of $20). If 2, then Crisis Cleanup will double-match (e.g., match $10 with $20 for a total of $30). Default is 1.
- [ ] Set a boolean `ccu_cover_fees`. If true, then CCU will cover credit card fees. Default is true.
- [ ] Set `expires_at`, or the timestamp when the offer expires. Default is 1 month from NOW().
- [ ] See a table of all pending (and completed) donation invitations
- [ ] Ability to resend a reminder to donate either in bulk or one at a time (kind of like a "Reinvite" button)
- [ ] See a table of all pending (and completed) transactions, including
  - [ ] transation_id
  - [ ] From (User's full name or email)
  - [ ] To (Organization Name & ID)
  - [ ] Transaction Type (e.g., userDonation, ccuMatch, ccuPayout)
  - [ ] Gross
  - [ ] Transaction status (e.g., pending, captured; or finalized/ ready)
  - [ ] Fees
  - [ ] Net
