### ISSUE TITLE
Create Matching Donations User Interface Tool

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#404]
## Description
Users who receive an invitation to make a matching donation to a CCU partner need an interface to choose the partner, pay, and receive a receipt of their payment. By default, this tool should suggest the user's organization, but give them the opportunity to choose one or more organizations to donate to. The interface should show how much money they are donating, to which organization, how much CCU will match, and the final amount the organization will receive.

## Tasks
This tool needs to allow the user to:
- [ ] Agree to special T&C and disclaimers
- [ ] Choose one or more organizations from a list to donate to.
- [ ] Filter organizations by multiple attributes, including impact, cases claimed or entered, capabilities, those participating in a particular disaster, number of disasters to which they deployed, commercial value of work accomplished or documented, etc.
- [ ] Distribute the CCU matching amount among the organizations chosen.
- [ ] Choose to donate anonymously or share their contact information with the organization.
- [ ] Provide backup instructions in case CCU is unable to contact the organization of choice. This is a free-form text that will have suggestions the user can choose from, which will enter into the free-form text field.
- [ ] Pay into a CCU account using a credit card, PayPal, or whatever, which will then be paid out to relief organizations at a later date, typically within a month.
