### ISSUE TITLE
Generate Incident Printed and Social Media Assets

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#405]
## Description
As a part of the incident creation process, we create social media assets and flyers in https://www.crisiscleanup.org/admin/incident_wizard. This process has not been finalized.

## Tasks
- [ ] Only implement when an incident has a hotline. (i.e. the date on the flyer). After that, they should automatically disappear from /disasters
- [ ] A single incident may have multiple hotlines. Produce a separate set of materials for each hotline. For example, we will produce 4-per-page handbills, door hangers, pull-tab flyer, and social media assets with the phone number, (4 products) in English and Spanish (2 languages). If there are two separate hotlines, then the total number of assets produced is 4 x 2 x 2 = 16.
- [ ] Optional: Choose a previous disaster to start from, for each asset. This will pre-populate each asset with the text from the chosen disaster as a starting point.
- [ ] The messaging may be slightly unique for each disaster. If the text is auto-generated, it must also be editable.
- [ ] Step 1: Choose the hotline(s) and activate them.
- [ ] Step 2: Select the assets for the system to create (e.g., Handbills, Door Hangers, Pull-tab Flyers, Social Media Assets).
- [ ] Step 3: Walk the user through each asset, for each hotline. Allow the user to manually edit text areas for each section of each asset. Limit the number of characters in each text area. Pre-populate the text with suggestions, including the hotline phone number. The last day should be the Friday before the end_at timestamp.
- [ ] Step 4: Preview. Set publish timestamp.
- [ ] Step 6: Save/ Publish.
- [ ] Text must be formattable (i.e. html) to permit bold, underline, links, etc.
