### ISSUE TITLE
Crisis Cleanup AU Checklist

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#599]
## Description
We recently launched crisiscleanup.org.au, and the following changes need to be made to this portal, ideally without forking the code. Whenever possible, these settings should be added to `portal_portals.attr`

## Add to portal_portal.attr
- [ ] Top-left icon should be AU
- [ ] Default language is 3 (`en-au`). This is in `attr`, but not implemented.
- [ ] Add `en-au` as a supported language, and a translate everything to `en-au` on both US and AU Production.
- [ ] The translation tool should translate from `en-au` instead of `en-us` to other languages.
- [ ] Change the link to the app download, to CCU AU instead of US app
- [ ] Ensure that emails are written in `en-au`. Basically, we need folders for all emails for multiple languages.
- [ ] Emails need to send from help@crisiscleanup.org.au
- [ ] Help link should be defined in `portal_portal.attr`, since we will need to create a new AU Zendesk
- [ ] Default map portal should be set in `portal_portal.attr`. Default map should be Australia.

## Actions
- [ ] Need to open up a new Zendesk for AU
- [ ] Update TOS and Privacy

## Bugs
- [ ] Navigation isn't working
- [ ] First login gives you the spinner of death.
- [x] Create a new portal in portal_portals

**Comment by aarontitus** [comment]
These are the AU logo assets: [CCU_AU_Logo_pms.zip](https://github.com/CrisisCleanup/crisiscleanup-4-web/files/13593117/CCU_AU_Logo_pms.zip)
