### ISSUE TITLE
Overhaul Phone Interface; Add LLM to Chat

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#671]
## Description
Overhaul the phone interface, per Figma. Add LLM "Suggestions" to chat.

## Screenshots
Do this (Top of the page, under "Fix Phone Tabs"):
https://www.figma.com/file/GA0bFEfJZ0FHVm9rw7koyk/Crisis-Web_Platform?type=design&node-id=3853-294301&mode=design&t=to6RGK4jMXQ9OlsL-0

## Tasks
- [ ] Green "Active Call" bar at top of screen.
- [ ] "Show Details" vertical fly-down for active call, pushes anything taking over the screen down almost to the bottom.
- [ ] Widget tabs expand to a full description, and contract to a single icon; "Active Call" expands or contracts to take up the entire vertical top portion of the screen.
- [ ] Clicking on a widget, the contents horizontally fly out to the left, and take over the entire map.
- [ ] Phone Chat:
  - [ ] Not shown: Don't forget to include favorite star and tab
  - [ ] Sort of shown: There is a floating gray "Phone chat" with a "Search phone chat" and "Close tab" floating between two screens. Use that.
  - [ ] "Online Now" section, showing first three users. Scrollable to show others online
  - [ ] Clicking on a person's name will "@" them
  - [ ] Suggestions with "Copy" button. "Copy" copies the suggestion to the clilpboard AND enters the suggestion into chat box.
  - [ ] Will need to add an "Expand" or "Show entire suggestion" option, with like three dots or something. Some suggestions will be long. See example below.

## Example long Suggestion response:
```
If you are experiencing the “Not Playing Nicely” error with Crisis Cleanup, here are the steps you can take to resolve the issue:

1. Click the “Not Playing Nicely” button to the right of the yellow “Take Calls” button on the Crisis Cleanup interface.
2. A dropdown selector will appear with three options: “Take Inbound and Outbound,” “Take Inbound Only,” and “Take Outbound Only.” The default setting is “Take Inbound and Outbound.”
3. Try choosing either “Take Inbound Only” or “Take Outbound Only” to limit the system to one type of call and remove the conflict.
4. The setting will automatically reset at midnight. If the issue persists, some volunteers report that waiting for 30 seconds can sometimes result in an inbound call coming through.
5. If the problem is still not resolved, you can try changing your phone number to a different one, preferably using a different phone carrier.
6. Click the bug button on the phone page and then click the “reset phone system” button.
7. After that, try taking calls again.

If none of these steps work, consider taking a break and giving yourself recognition for the support you provide to survivors on some of their hardest days. The “Not Playing Nicely” error is an “offhook” error and can be caused by several issues that are outside of Crisis Cleanup’s control. Limiting the system to either inbound or outbound calls should remove this conflict (Crisis Cleanup User Guide).

Remember, the setting will automatically reset at midnight, so you may need to repeat these steps if the issue occurs again after the reset.
```

**Comment by BradenM** [comment]
Partially done on adding LLM to chat. Maybe extract as a separate issue
