### ISSUE TITLE
UI: Table Improvements

### ISSUE THREAD

**Issue by deepanchal** [CrisisCleanup/crisiscleanup-4-web#695]
## Table improvements suggestions from Zac

![Image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/46167867/026eb545-f2a7-472b-a9f7-9248548a5980)

```[tasklist]
### Tasks
- [x] Vertically center incident icon with incident selector in <Header>
- [x] Hide layers button for list case view in work & phone page
- [x] Table view on work & phone page should take full height and be responsive vertically
- [x] Make table view action buttons left aligned
- [x] Make button disabled state darker
- [x] Switch active nav yellow border from left to right side, make it a little thicker
- [x] Remove double arrow refresh on update status button in table view for work & phone page
- [x] Remove white border from global container
- [x] Make page header to the left of incident selector (just testing how it looks)
- [x] Table on Organization > Layers Library should take full height
- [x] Table on Other organizations should take full height
- [x] Table pagination pageSize options should open on `top` direction instead of `bottom`
```

**Comment by deepanchal** [comment]
Closed by #699 #767
